# MoveIt uses this configuration for controller management
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - scara_arm_controller
    - scara_gripper_controller

  scara_arm_controller:
    type: FollowJointTrajectory
    action_ns: scara_arm_controller
    default: true
    joints:
      - Revolute 10
      - Revolute 7
      - Revolute 8
      - Slider 11
      - Slider 4
      - Slider 5

  scara_gripper_controller:
    type: FollowJointTrajectory
    action_ns: scara_gripper_controller
    default: false
    joints:
      - Revolute 7
      - Slider 4
      - Slider 5